[package]
name = "Immersive Vehicles"
description = "A mod that adds real-time travel with a number of vehicles."
homepage = "https://www.nexusmods.com/morrowind/mods/54333"
repository = "https://github.com/rfuzzo/tes3-mods"
authors = ["rfuzzo"]
version = "0.1.1"

[tools.mwse]
lua-mod = "ImmersiveVehicles"

[dependencies.mwse]
buildnumber = 3676

[dependencies.mods."ImmersiveVehicles"]
mwse-module = "rfuzzo.ImmersiveTravel"
